apiVersion: v1
kind: Service
metadata:
  name: devops-enterprise-service
  namespace: NAMESPACE
spec:
  selector:
    app: devops-enterprise
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 30009
  type: SERVICE_TYPE
